### ISSUE TITLE
version command should exit 0

### ISSUE THREAD

**Issue by mr-c** [indigo-dc/udocker#107]
```
$ ./udocker version; echo Return code: $?
version: 1.1.1
tarball: https://owncloud.indigo-datacloud.eu/index.php/s/AFImjw8ii0X72xf/download https://cernbox.cern.ch/index.php/s/VC7GuVWA7mYRAiy/download http://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/tgz/udocker-1.1.1.tar.gz
Return code: 1
```

```
$ docker version; echo Return code: $?
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
Return code: 0
```

**Comment by mr-c** [comment]
Fixed in https://github.com/indigo-dc/udocker/commit/5237ef585206e355ed5c6e1142915b94e546f157 which is not yet released.

**Comment by yuvipanda** [comment]
This now fails with:

```
23:50 $ ./udocker version
Traceback (most recent call last):
  File "./udocker", line 7050, in <module>
    sys.exit(Main().start())
  File "./udocker", line 6961, in __init__
    self._version()
AttributeError: 'Main' object has no attribute '_version'
```

In the devel branch.

**Comment by jorge-lip** [comment]
Fixed on devel
