### ISSUE TITLE
udocker not able to load OCI images

### ISSUE THREAD

**Issue by frezbo** [indigo-dc/udocker#111]
I build an OCI complaint image using **umoci** and  I can load it pretty fine with **docker load**, but **udocker load** is failing

```
Warning: unkwnon file in image: /tmp/udocker-19-f6c1c0f1-b4c0-3c42-91fa-44908957118d-import/sha256:37ecd960a269fa495e2667eb9e4151c6af35441b5fb78273eb3d2a57f811916c
Warning: unkwnon file in image: /tmp/udocker-19-f6c1c0f1-b4c0-3c42-91fa-44908957118d-import/sha256:d7e33c1a7ea84f534a4345e60d3f7514e7f12db8f363f4332d71514d4119a3b5
Traceback (most recent call last):
  File "/usr/local/bin/udocker", line 6663, in <module>
    sys.exit(Main().start())
  File "/usr/local/bin/udocker", line 6651, in start
    exit_status = self.execute()
  File "/usr/local/bin/udocker", line 6635, in execute
    status = cmds[command](self.cmdp)     # executes the command
  File "/usr/local/bin/udocker", line 5630, in do_load
    repos = self.dockerlocalfileapi.load(imagefile)
  File "/usr/local/bin/udocker", line 5320, in load
    repositories = self._load_image(structure, imagerepo, tag)
  File "/usr/local/bin/udocker", line 5250, in _load_image
    top_layer_id = self._find_top_layer_id(structure)
  File "/usr/local/bin/udocker", line 5189, in _find_top_layer_id
    my_layer_id = structure["layers"].keys()[0]
IndexError: list index out of range
```

This is my Dockerfile

```
FROM debian:sid-slim AS test-rootfs
LABEL maintainer "noel[dot]georgi[at]reancloud[dot]com"
ARG CHEFDK_VERSION=13.6.4-1
RUN apt-get update && \
    apt-get install --no-install-recommends -y ansible python-pip curl && \
    curl https://omnitruck.chef.io/install.sh | bash -s -- -P chef -v ${CHEFDK_VERSION} && \
    pip install awscli && \
    apt-get purge -y python-pip && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/ && \
    mkdir -p /opt/data

FROM alpine:3.7 AS umoci
ARG UMOCI_URL=https://github.com/openSUSE/umoci/releases/download/v0.3.1/umoci.amd64
ARG UMOCI_ASC=https://github.com/openSUSE/umoci/releases/download/v0.3.1/umoci.amd64.asc
ARG UMOCI_SHA256=68a4d5864d936bf6e3826dc0147c45f081d1c0b047cbb30f97d13df7d890dc5d
ARG GPG_KEYSERVER=keyserver.opensuse.org
ARG GPG_KEY=9E18AA267DDB8DB4
RUN apk update --no-cache && \
    apk add curl gnupg && \
    gpg --keyserver ${GPG_KEYSERVER} --recv-key ${GPG_KEY} && \
    curl -SL -o $(basename ${UMOCI_URL}) ${UMOCI_URL} && \
    curl -SL -o $(basename ${UMOCI_ASC}) ${UMOCI_ASC} && \
    echo "${UMOCI_SHA256}  $(basename  ${UMOCI_URL})" | sha256sum -c && \
    gpg --batch --verify $(basename ${UMOCI_ASC}) $(basename ${UMOCI_URL}) && \
    mv $(basename ${UMOCI_URL}) /usr/local/bin/umoci && \
    chmod +x /usr/local/bin/umoci

FROM alpine:3.7 AS oci-image-builder
COPY --from=umoci /usr/local/bin/umoci /usr/local/bin/umoci
RUN umoci init --layout test && \
    umoci new --image test:latest && \
    umoci unpack --image test:latest test-oci
COPY --from=test-rootfs / test-oci/rootfs/
RUN umoci repack --image test:latest test-oci/

FROM ubuntu:17.04 as skopeo
ARG SKOPEO_REPO=https://github.com/projectatomic/skopeo.git
RUN apt-get update && apt-get install -y \
    golang \
    btrfs-tools \
    git-core \
    libdevmapper-dev \
    libgpgme11-dev \
    go-md2man \
    libglib2.0-dev \
    libostree-dev
ENV GOPATH=/
WORKDIR /src/github.com/projectatomic/
    RUN git clone ${SKOPEO_REPO} && \
    cd skopeo && \
    make binary-local && \
    cp skopeo /usr/local/bin/
COPY docker/policy.json /etc/containers/
WORKDIR /
COPY --from=oci-image-builder /test/ /test/
RUN skopeo copy oci:test docker-archive:test.tar.gz:test:latest

FROM alpine:3.7 AS udocker-installer
ARG UDOCKER_URL=https://raw.githubusercontent.com/indigo-dc/udocker/master/udocker.py
RUN apk update && \
    apk add curl && \
    curl -o /usr/local/bin/udocker ${UDOCKER_URL} && \
    chmod +x /usr/local/bin/udocker

FROM ${ARTIFACTORY}/${ENVIRONMENT}/tomcat:${TAG}
COPY --from=udocker-installer /usr/local/bin/udocker /usr/local/bin/udocker
COPY --from=skopeo --chown=tomcat:tomcat /test.tar.gz /tmp/
USER root
RUN apk add --no-cache python tar findutils file su-exec bash && \
	su-exec tomcat udocker install && \
    su-exec tomcat udocker load -i /tmp/test.tar.gz
```

**Comment by jorge-lip** [comment]
Added loading of OCI images to the latest production release [1.1.4](https://github.com/indigo-dc/udocker/tree/v1.1.4).

**Comment by jorge-lip** [comment]
Closing this ticked, please reopen if necessary.
