### ISSUE TITLE
Problem importing container into another system

### ISSUE THREAD

**Issue by smcgrat** [indigo-dc/udocker#147]
Hi guys. Some quick things before I detail the issue I'm having

1. Thanks for udocker, its really useful.
2. If I have missed something blatant or am misunderstanding something, sorry about that.
3. I know we aren't supposed to build containers with udocker and that is what I am doing here but to be honest, udocker is the easiest container build system I have encountered. Sorry.

I am having a problem importing a container from one system to another.

I have built a container to run TensorFlow that works on system  1. 
Cluster 1
```
$ uname -r; cat /etc/redhat-release 
2.6.32-696.30.1.el6.x86_64
Scientific Linux release 6.9 (Carbon)
$ udocker pull ubuntu:16.04
$ udocker create --name=tfcon ubuntu:16.04
$ udocker run tfcon bash
# apt update && apt install -y gcc kmod perl python3 python3-pip
# pip3 install tensorflow==1.5
# python3
>>> import tensorflow as tf
>>> quit()
# exit
```

Then exported it from cluster 1:
```
$ udocker export -o tfcon.tar tfcon
```

Copied the tar across and tried to run it on cluster 2 as follows with the ensuing python error:

Cluster 2
```
$ uname -r; cat /etc/redhat-release 
3.10.0-862.3.3.el7.x86_64
Scientific Linux release 7.5 (Nitrogen)
$ udocker import tfcon.tar tfcon
$ udocker run tfcon bash
 
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING 3910746f-c23e-32b1-ac76-aeb1e92f4f72                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: bash
root@container:/# python3
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 580, in <module>
    main()
  File "/usr/lib/python3.5/site.py", line 566, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.5/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.5/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.5/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
ValueError: source code string cannot contain null bytes
```

This is probably something fairly simple and obvious I'm missing, sorry for that. If anyone can point out what I am doing wrong I would be very grateful.

Regards

Sean

**Comment by jorge-lip** [comment]
Sorry we have been unable to reproduce the problem. Could you try with the latest udocker in the master branch and report if still happens.

**Comment by jorge-lip** [comment]
No activity closing this ticket.
