### ISSUE TITLE
Udocker does install in Termux on Android smartphone!

### ISSUE THREAD

**Issue by sdrausty** [indigo-dc/udocker#152]
I'm trying to get this installed on my smartphone https://github.com/termux/termux-packages/issues/2755 via Termux:
```
[13:16 indigo-dc ]$ git clone https://github.com/indigo-dc/udocker
Cloning into 'udocker'...
remote: Counting objects: 1789, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 1789 (delta 25), reused 25 (delta 11), pack-reused 1747
Receiving objects: 100% (1789/1789), 1.90 MiB | 10.00 KiB/s, done.
Resolving deltas: 100% (1063/1063), done.
[13:19 indigo-dc ]$ cd udocker/
[13:20 udocker ]$  ./udocker.py install
Traceback (most recent call last):
  File "./udocker.py", line 6663, in <module>
    sys.exit(Main().start())
  File "./udocker.py", line 6596, in __init__
    self.udocker = Udocker(self.localrepo)
  File "./udocker.py", line 5505, in __init__
    self.dockerioapi = DockerIoAPI(localrepo)
  File "./udocker.py", line 4662, in __init__
    self.curl = GetURL()
  File "./udocker.py", line 4377, in __init__
    self._select_implementation()
  File "./udocker.py", line 4385, in _select_implementation
    elif GetURLexeCurl().is_available():
  File "./udocker.py", line 4545, in is_available
    return bool(FileUtil("curl").find_exec())
  File "./udocker.py", line 929, in find_exec
    cmd = self._find_exec("which " + self.basename)
  File "./udocker.py", line 921, in _find_exec
    if "not found" in exec_pathname:
TypeError: a bytes-like object is required, not 'str'
[13:23 udocker ]$ 
```

**Comment by sdrausty** [comment]
The result is similar, but not identical with Arch Linux in Termux PRoot:
```
[13:56 home ]$ cd git/indigo-dc/udocker/
[13:57 udocker ]$ ./udocker.py install
Traceback (most recent call last):                                                          File "./udocker.py", line 6663, in <module>
    sys.exit(Main().start())
  File "./udocker.py", line 6596, in __init__                                                 self.udocker = Udocker(self.localrepo)
  File "./udocker.py", line 5505, in __init__                                                 self.dockerioapi = DockerIoAPI(localrepo)
  File "./udocker.py", line 4662, in __init__
    self.curl = GetURL()                                                                    File "./udocker.py", line 4377, in __init__
    self._select_implementation()
  File "./udocker.py", line 4385, in _select_implementation                                   elif GetURLexeCurl().is_available():
  File "./udocker.py", line 4545, in is_available
    return bool(FileUtil("curl").find_exec())                                               File "./udocker.py", line 929, in find_exec                                                 cmd = self._find_exec("which " + self.basename)
  File "./udocker.py", line 921, in _find_exec
    if "not found" in exec_pathname:
TypeError: a bytes-like object is required, not 'str'
[13:57 udocker ]$
```

**Comment by sdrausty** [comment]
> Udocker appears to suffer from the same affliction as gradle, and some others do too: exclusive x86 dependency; Do you agree?



Is udocker exclusive to x86 architecture?  Can it run on arm architectures?

**Comment by mr-c** [comment]
Looks like you're running `udocker` with Python 3? It is Python 2 only: https://github.com/indigo-dc/udocker/issues/131

As for the architecture, it may work on others, but you'd need to build your own `proot` binaries, etc.: https://github.com/indigo-dc/udocker/blob/master/doc/installation_manual.md#6-build

**Comment by sdrausty** [comment]
@mr-c thank you for this information; udocker installs in Termux https://github.com/termux/termux-packages/issues/2755!

**Comment by arushijain71** [comment]
Is anyone here got success in installing udocker in Android?
I am trying with Termux but got stuck at: "_Error installing tarball, error installing udocker tools failed_"

**Comment by SDRausty** [comment]
@arushijain71 [udocker installs in Arch Linux in Termux PRoot on Android 9](https://github.com/SDRausty/TermuxArch/issues/102#issuecomment-660638859).  Python2 was used.  The error that crops up on Android 10 is:
```
$ python2 setup.py
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
```
Does anyone know how to resolve this error?
```
$ pip install setuptools
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (49.2.0)
```

**Comment by mr-c** [comment]
@SDRausty try `pip2 install setuptools` or `python2 -m pip install setuptools`

**Comment by SDRausty** [comment]
@mr-c thank you for sharing.  The commands `pacman -S python2-pip && pip2 install setuptools` have got `udocker` running on Android 10:
```
[user15:55udocker]$ udocker pull cfmanteiga/alpine-bash-curl-jq           
Downloading layer: sha256:fe2a0d033fc4104cf66bed5e778d032a5d582c10c4683f1bac9b0d43f4c380ef                                                    
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4                                                    
Downloading layer: sha256:e61ca54ed02c6c26cf7adfdc655cd6ecb61dd63137899968404d22f49296364d                                                    
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4                                                    
[user15:55udocker]$ udocker images                                        
REPOSITORY                                                             
cfmanteiga/alpine-bash-curl-jq:latest
[user15:56udocker]$
```
Do you know the next command and a good simple docker primer?

**Comment by SDRausty** [comment]
There are errors when using the command run:
```
$ udocker run k8spatterns/curl-jq:latest                  Warning: non-existing user will be created
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/udocker", line 4, in <module>
    __import__('pkg_resources').run_script('udocker==1.1.4', 'udocker')
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/udocker-1.1.4-py2.7.egg/EGG-INFO/scripts/udocker", line 8547, in <module>
    sys.exit(Main().start())
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/udocker-1.1.4-py2.7.egg/EGG-INFO/scripts/udocker", line 8535, in start
    exit_status = self.execute()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/udocker-1.1.4-py2.7.egg/EGG-INFO/scripts/udocker", line 8518, in execute
    status = cmds[command](self.cmdp)     # executes the command
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/udocker-1.1.4-py2.7.egg/EGG-INFO/scripts/udocker", line 7782, in do_run
    status = exec_engine.run(container_id)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/udocker-1.1.4-py2.7.egg/EGG-INFO/scripts/udocker", line 3244, in run
    self.select_proot()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/udocker-1.1.4-py2.7.egg/EGG-INFO/scripts/udocker", line 3189, in select_proot
    if HostInfo().oskernel_isgreater((4, 8, 0)):
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/udocker-1.1.4-py2.7.egg/EGG-INFO/scripts/udocker", line 506, in oskernel_isgreater
    os_version = [int(x) for x in os_release.split('.')[0:3]]
ValueError: invalid literal for int() with base 10: '146+'
```
This command `udocker run --hostauth --hostenv --bindhome k8spatterns/curl-jq:latest` gives the same rresult.
