### ISSUE TITLE
[devel3] udocker setup --execmode=F3 ubuntu FAILS

### ISSUE THREAD

**Issue by mariojmdavid** [indigo-dc/udocker#227]
Traceback (most recent call last):
  File "/home/ubuntu/udocker/udocker", line 32, in <module>
    UMain(sys.argv).start()
  File "/home/ubuntu/udocker/../udocker/umain.py", line 125, in start
    exit_status = self._execute()
  File "/home/ubuntu/udocker/../udocker/umain.py", line 110, in _execute
    exit_status = cmds[command](self.cmdp)  # executes command
  File "/home/ubuntu/udocker/../udocker/cli.py", line 953, in do_setup
    status = exec_mode.set_mode(xmode.upper(), force)
  File "/home/ubuntu/udocker/../udocker/engine/execmode.py", line 81, in set_mode
    status = (elfpatcher.patch_ld() and
  File "/home/ubuntu/udocker/../udocker/helper/elfpatcher.py", line 198, in patch_ld
    ld_data = ld_data.replace(etc, nul_etc).\
TypeError: a bytes-like object is required, not 'str'

this traces to udocker/utils/fileutil.py getdata(self, mode="rb") and putdata(self, mode="rb") methods

**Comment by mariojmdavid** [comment]
solved in devel3 based on 1.1.4 rel
