### ISSUE TITLE
run --dri broken in S1 mode

### ISSUE THREAD

**Issue by katakombi** [indigo-dc/udocker#241]
Again on `devel`. Not sure how the directories for the --dri bind flag are determined, but it doesn't seem to be functional currently. When using S1 mode I get with an arbitrary container:

```
./udocker run --dri test bash
Warning: non-existing user will be created
Traceback (most recent call last):
  File "./udocker", line 8388, in <module>
    sys.exit(Main().start())
  File "./udocker", line 8376, in start
    exit_status = self.execute()
  File "./udocker", line 8359, in execute
    status = cmds[command](self.cmdp)     # executes the command
  File "./udocker", line 7664, in do_run
    status = exec_engine.run(container_id)
  File "./udocker", line 3728, in run
    if not self._run_init(container_id):
  File "./udocker", line 3008, in _run_init
    if not self._set_volume_bindings():
  File "./udocker", line 2532, in _set_volume_bindings
    return self._check_volumes()
  File "./udocker", line 2491, in _check_volumes
    if not self._create_mountpoint(host_path, cont_path):
  File "./udocker", line 2469, in _create_mountpoint
    if self.mountp.create(host_path, cont_path):
  File "./udocker", line 2256, in create
    if not status:
UnboundLocalError: local variable 'status' referenced before assignment
```

Seems like an else path is missing. When I catch it I get
```
Warning: non-existing user will be created
Error: creating container mountpoint: /usr/lib64/dri
Error: creating mountpoint: /usr/lib64/dri /usr/lib64/dri
```

**Comment by katakombi** [comment]
Happens on LinuxMint, doesn't on Fedora 29.

**Comment by jorge-lip** [comment]
Hi,
Could you try with the latest version in devel.

**Comment by katakombi** [comment]
No change

```
UDOCKER_DEFAULT_EXECUTION_MODE=S1 ./udocker.py run --dri alpine sh
Warning: non-existing user will be created
Traceback (most recent call last):
  File "./udocker", line 8542, in <module>
    sys.exit(Main().start())
  File "./udocker", line 8530, in start
    exit_status = self.execute()
  File "./udocker", line 8513, in execute
    status = cmds[command](self.cmdp)     # executes the command
  File "./udocker", line 7777, in do_run
    status = exec_engine.run(container_id)
  File "./udocker", line 3825, in run
    if not self._run_init(container_id):
  File "./udocker", line 3132, in _run_init
    if not self._set_volume_bindings():
  File "./udocker", line 2675, in _set_volume_bindings
    return self._check_volumes()
  File "./udocker", line 2626, in _check_volumes
    if not self._create_mountpoint(host_path, cont_path):
  File "./udocker", line 2604, in _create_mountpoint
    if self.mountp.create(host_path, cont_path):
  File "./udocker", line 2385, in create
    if not status:
UnboundLocalError: local variable 'status' referenced before assignment
```

**Comment by jorge-lip** [comment]
Should be ok now ...

**Comment by katakombi** [comment]
Thanks a lot, @jorge-lip, head of devel fixes this for me!
